#!/bin/bash

#
# kubens(1) is a utility to switch between Kubernetes namespaces
#
#
# maintainer AATHITH_RAJENDRAN
cmd=$1

declare -A arg1
arg1[name]=".metadata.name"
arg1[status]=".status.phase"
arg1[restarts]=".status.containerStatuses[0].restartCount"
arg1[age]=".status.startTime"
arg1[ip]=".status.podIP"
arg1[node]=".spec.nodeName"

echo $option

if [ "$#" -eq 1 ];
then
  option=${arg1[$cmd]}
  echo "kubectl --sort-by=$option get po"
  kubectl --sort-by=$option get po

elif [ "$#" -eq 2 ];
then
  option=${arg1[$cmd]}
  namespace=$2

  if [ $2 = "all" ];
  then
  echo  "kubectl --sort-by=$option get po --all-namespaces"
    kubectl --sort-by=$option get po --all-namespaces
  else
  echo  "kubectl --sort-by=$option get po -n $namespace"
    kubectl --sort-by=$option get po -n $namespace
  fi

else
  cat << EOF
  kubesort sortby namespace_name
 
          sortby: name      # kubectl --sort-by=.metadata.name get po
                  status    # kubectl --sort-by=.status.phase get po
                  restarts  # kubectl --sort-by=.status.containerStatuses[0].restartcount get po
                  age       # kubectl --sort-by=.status.startTime get po
                  ip        # kubectl --sort-by=.status.podIP get po
                  node      # kubectl --sort-by=.spec.nodeName get po
                  help      # List available commands
  namespace_name: all              # kubectl --sort-by=option get po --all-namespaces
                  namespace_name   # kubectl --sort-by=option get po -n namespace_name
EOF
fi

